print("CV")
print("Iaroslava","Dubitkaia")
print("16.03.2005")
print("iaroslava.posta@gmail.com")
print("060529990")
print("Aurel Vlaicu 9")
print("poloneza")
print("I.P.L.T. Mihai Eminescu")
print("limba engleza, limba franceza")
print("limba romana")